# 异常

# 

```java
颜群老师微信：157468995
```



## 简介

 try

{

​	一切正常，执行这里

}catch(Exception e)

{

​    如果不正常，执行这里（异常）

}



int[] nums = new int[3] ;

try

{

​	nums[n]一切正常，执行这里

}catch(Exception e)

{

​    nums[n]如果不正常，执行这里（异常）

}

如果代码出现问题时，使用“异常机制”比 选择结构 更加方便。

## 异常的继承结构图

![1583199278029](异常.assets/1583199278029.png)



运行时异常：代码在编辑（编译阶段）时 不报错，运行时才报错。语法上，	可以选择性处理。

检查异常：代码在编辑（编译阶段）时报错。在编辑时，必须处理。



## 异常重点

try  catch  finally  throws  throw 

处理异常：try catch  或者 throws

try: 将可能发生异常的代码 用{}包裹起来


catch : 捕获特定类型的异常；捕获时，先写范围小的类型，后写范围大的类型

如果try中的代码的确发生了异常，则程序 不再执行try中异常之后的代码，而是直接跳到cath中执行

```java
public class Demo01 {
    public static void main(String[] args) {
        int[] nums = new int[3] ;
        System.out.println(nums[3]);//运行时异常，选择性处理
//

//       Class.forName("ex.Demo01");//检查异常，强制处理
    }
}
```




### try  catch

自己（当前方法）能够处理，使用try catch .

### throws  

自己（当前方法）不能处理，上交给 上级（方法调用处）处理  ,使用throws .

```java
    public static void test04() throws NullPointerException,ClassNotFoundException{//抛出异常，抛出给上级（方法调用处）
            Object obj = null   ;
            obj.equals("") ;//空指针
            Class.forName("xxx") ;
    }

    public static void main(String[] args) throws Exception{//继续往上抛出异常(JVM)
            test04();//异常
    }
```



### finally

无论正常，还是异常，始终都会执行的代码

不论执行完try，还是执行完catch，最终都会执行finally的代码

1.即使遇到return ,也仍然会执行finally

2.除非虚拟机关闭，才不会执行finally

```java
package ex;

/*
 * Created by 颜群
 */
public class Demo02 {

    public static void test01(){

        Object obj = null   ;
        try {
//            System.out.println("111");
            obj.equals("");//可能产生异常的代码
//            System.out.println("222");
//            System.out.println("正常时，关闭资源。。。");
        }catch (NullPointerException e){//捕获特定类型的异常
//            System.out.println("异常。。。");
//            System.out.println("发生了空指针异常。。");
//            System.out.println("异常时，关闭资源。。。");
        }finally{
            System.out.println("无论正常，还是异常，始终都会执行的代码。。。");
        }
    }

    public static int test02(){
        try{
            Object obj = null   ;

            System.exit(1);//关闭jvm
            obj.equals("") ;
            return 1 ;
        }catch (NullPointerException e){
                return 0 ;
        }finally{
            System.out.println("finally...");
        }
    }

    public static void main(String[] args) {
        test02() ;



    }
}

```



### 多个catch块

```java
   public static void test03(){
        try{
            Class.forName("xxx") ;
            Object obj = null   ;
            obj.equals("") ;//空指针

            int[] nums = new int[3] ;
           nums[3] = 3 ;//数组越界异常

        }catch (NullPointerException e){//捕获空指针
            System.out.println("空指针异常..");
        }catch (ArrayIndexOutOfBoundsException e){
            System.out.println("数组越界异常...");
        }catch (Exception e) {//还有一些 根本临时想不到的异常
            System.out.println("其他异常。。。");
        }
    }
```



### throw 一般和 自定义异常 一起使用

throw: 声明异常

jdk中自带了很多类型的异常，但如果 这些内置的异常 仍然不能满足项目的需求，那么就需要创建 自定义异常。

如何编写自定义异常：

1类，继承Exception，调用super(“异常信息”)

```java
package ex;

/*
 * Created by 颜群
 */
//public class MyException  extends  Throwable{
//public class MyException  extends  NullPointerException{
public class MyException  extends  Exception{//推荐
    public MyException(String message){//异常信息
        super(message);
    }
}


```

2.使用throw 声明一个自定义异常、并且进行try catch或throws

```java
package ex;

/*
 * Created by 颜群
 */
public class Demo03 {

    public static void main(String[] args)   {
        int age = 188 ;
        //约定，年龄不能大于120
        if(age<= 0 || age>120){
            try {
                //手工声明一个异常
                throw new MyException("年龄不能大于120");
            }catch ( MyException e ){
                e.printStackTrace();
                System.out.println(e.getMessage());
            }
        }
    }
}

```

在开发的过程中，要逐步积累异常，有助于提高我们的 排查bug的能力。





